//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RedeSocialContext", "FK_Album_Tema", "Tema", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RedeSocialEF4.Tema), "Album", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RedeSocialEF4.Album), true)]
[assembly: EdmRelationshipAttribute("RedeSocialContext", "FK_Album_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RedeSocialEF4.Usuario), "Album", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RedeSocialEF4.Album), true)]
[assembly: EdmRelationshipAttribute("RedeSocialContext", "FK_Foto_Album", "Album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RedeSocialEF4.Album), "Foto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RedeSocialEF4.Foto), true)]
[assembly: EdmRelationshipAttribute("RedeSocialContext", "FK_Comentario_Foto", "Foto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RedeSocialEF4.Foto), "Comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RedeSocialEF4.Comentario), true)]
[assembly: EdmRelationshipAttribute("RedeSocialContext", "FK_Comentario_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RedeSocialEF4.Usuario), "Comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RedeSocialEF4.Comentario), true)]
[assembly: EdmRelationshipAttribute("RedeSocialContext", "Amizade", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RedeSocialEF4.Usuario), "Usuario1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RedeSocialEF4.Usuario))]

#endregion

namespace RedeSocialEF4
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RedeSocialEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RedeSocialEntities object using the connection string found in the 'RedeSocialEntities' section of the application configuration file.
        /// </summary>
        public RedeSocialEntities() : base("name=RedeSocialEntities", "RedeSocialEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RedeSocialEntities object.
        /// </summary>
        public RedeSocialEntities(string connectionString) : base(connectionString, "RedeSocialEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RedeSocialEntities object.
        /// </summary>
        public RedeSocialEntities(EntityConnection connection) : base(connection, "RedeSocialEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Album> Albuns
        {
            get
            {
                if ((_Albuns == null))
                {
                    _Albuns = base.CreateObjectSet<Album>("Albuns");
                }
                return _Albuns;
            }
        }
        private ObjectSet<Album> _Albuns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comentario> Comentarios
        {
            get
            {
                if ((_Comentarios == null))
                {
                    _Comentarios = base.CreateObjectSet<Comentario>("Comentarios");
                }
                return _Comentarios;
            }
        }
        private ObjectSet<Comentario> _Comentarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Foto> Fotos
        {
            get
            {
                if ((_Fotos == null))
                {
                    _Fotos = base.CreateObjectSet<Foto>("Fotos");
                }
                return _Fotos;
            }
        }
        private ObjectSet<Foto> _Fotos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tema> Temas
        {
            get
            {
                if ((_Temas == null))
                {
                    _Temas = base.CreateObjectSet<Tema>("Temas");
                }
                return _Temas;
            }
        }
        private ObjectSet<Tema> _Temas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Albuns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlbuns(Album album)
        {
            base.AddObject("Albuns", album);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comentarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComentarios(Comentario comentario)
        {
            base.AddObject("Comentarios", comentario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Fotos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFotos(Foto foto)
        {
            base.AddObject("Fotos", foto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Temas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTemas(Tema tema)
        {
            base.AddObject("Temas", tema);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RedeSocialContext", Name="Album")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Album : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Album object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="dataCriacao">Initial value of the DataCriacao property.</param>
        /// <param name="idTema">Initial value of the IdTema property.</param>
        /// <param name="idPessoa">Initial value of the IdPessoa property.</param>
        public static Album CreateAlbum(global::System.Int32 id, global::System.String nome, global::System.String descricao, global::System.DateTime dataCriacao, global::System.Int32 idTema, global::System.Int32 idPessoa)
        {
            Album album = new Album();
            album.Id = id;
            album.Nome = nome;
            album.Descricao = descricao;
            album.DataCriacao = dataCriacao;
            album.IdTema = idTema;
            album.IdPessoa = idPessoa;
            return album;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCriacao
        {
            get
            {
                return _DataCriacao;
            }
            set
            {
                OnDataCriacaoChanging(value);
                ReportPropertyChanging("DataCriacao");
                _DataCriacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataCriacao");
                OnDataCriacaoChanged();
            }
        }
        private global::System.DateTime _DataCriacao;
        partial void OnDataCriacaoChanging(global::System.DateTime value);
        partial void OnDataCriacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTema
        {
            get
            {
                return _IdTema;
            }
            set
            {
                OnIdTemaChanging(value);
                ReportPropertyChanging("IdTema");
                _IdTema = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTema");
                OnIdTemaChanged();
            }
        }
        private global::System.Int32 _IdTema;
        partial void OnIdTemaChanging(global::System.Int32 value);
        partial void OnIdTemaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPessoa
        {
            get
            {
                return _IdPessoa;
            }
            set
            {
                OnIdPessoaChanging(value);
                ReportPropertyChanging("IdPessoa");
                _IdPessoa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPessoa");
                OnIdPessoaChanged();
            }
        }
        private global::System.Int32 _IdPessoa;
        partial void OnIdPessoaChanging(global::System.Int32 value);
        partial void OnIdPessoaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Album_Tema", "Tema")]
        public Tema Tema
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tema>("RedeSocialContext.FK_Album_Tema", "Tema").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tema>("RedeSocialContext.FK_Album_Tema", "Tema").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tema> TemaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tema>("RedeSocialContext.FK_Album_Tema", "Tema");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tema>("RedeSocialContext.FK_Album_Tema", "Tema", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Album_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RedeSocialContext.FK_Album_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RedeSocialContext.FK_Album_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RedeSocialContext.FK_Album_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("RedeSocialContext.FK_Album_Usuario", "Usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Foto_Album", "Foto")]
        public EntityCollection<Foto> Fotos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Foto>("RedeSocialContext.FK_Foto_Album", "Foto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Foto>("RedeSocialContext.FK_Foto_Album", "Foto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RedeSocialContext", Name="Comentario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comentario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comentario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idFoto">Initial value of the IdFoto property.</param>
        /// <param name="idPessoa">Initial value of the IdPessoa property.</param>
        /// <param name="texto">Initial value of the Texto property.</param>
        /// <param name="dataCadastro">Initial value of the DataCadastro property.</param>
        /// <param name="aprovado">Initial value of the Aprovado property.</param>
        public static Comentario CreateComentario(global::System.Int32 id, global::System.Int32 idFoto, global::System.Int32 idPessoa, global::System.String texto, global::System.DateTime dataCadastro, global::System.Boolean aprovado)
        {
            Comentario comentario = new Comentario();
            comentario.Id = id;
            comentario.IdFoto = idFoto;
            comentario.IdPessoa = idPessoa;
            comentario.Texto = texto;
            comentario.DataCadastro = dataCadastro;
            comentario.Aprovado = aprovado;
            return comentario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFoto
        {
            get
            {
                return _IdFoto;
            }
            set
            {
                OnIdFotoChanging(value);
                ReportPropertyChanging("IdFoto");
                _IdFoto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdFoto");
                OnIdFotoChanged();
            }
        }
        private global::System.Int32 _IdFoto;
        partial void OnIdFotoChanging(global::System.Int32 value);
        partial void OnIdFotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPessoa
        {
            get
            {
                return _IdPessoa;
            }
            set
            {
                OnIdPessoaChanging(value);
                ReportPropertyChanging("IdPessoa");
                _IdPessoa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPessoa");
                OnIdPessoaChanged();
            }
        }
        private global::System.Int32 _IdPessoa;
        partial void OnIdPessoaChanging(global::System.Int32 value);
        partial void OnIdPessoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCadastro
        {
            get
            {
                return _DataCadastro;
            }
            set
            {
                OnDataCadastroChanging(value);
                ReportPropertyChanging("DataCadastro");
                _DataCadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataCadastro");
                OnDataCadastroChanged();
            }
        }
        private global::System.DateTime _DataCadastro;
        partial void OnDataCadastroChanging(global::System.DateTime value);
        partial void OnDataCadastroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Aprovado
        {
            get
            {
                return _Aprovado;
            }
            set
            {
                OnAprovadoChanging(value);
                ReportPropertyChanging("Aprovado");
                _Aprovado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Aprovado");
                OnAprovadoChanged();
            }
        }
        private global::System.Boolean _Aprovado;
        partial void OnAprovadoChanging(global::System.Boolean value);
        partial void OnAprovadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Comentario_Foto", "Foto")]
        public Foto Foto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Foto>("RedeSocialContext.FK_Comentario_Foto", "Foto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Foto>("RedeSocialContext.FK_Comentario_Foto", "Foto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Foto> FotoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Foto>("RedeSocialContext.FK_Comentario_Foto", "Foto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Foto>("RedeSocialContext.FK_Comentario_Foto", "Foto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Comentario_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RedeSocialContext.FK_Comentario_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RedeSocialContext.FK_Comentario_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("RedeSocialContext.FK_Comentario_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("RedeSocialContext.FK_Comentario_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RedeSocialContext", Name="Foto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Foto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Foto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="dataCadastro">Initial value of the DataCadastro property.</param>
        /// <param name="idAlbum">Initial value of the IdAlbum property.</param>
        public static Foto CreateFoto(global::System.Int32 id, global::System.String descricao, global::System.DateTime dataCadastro, global::System.Int32 idAlbum)
        {
            Foto foto = new Foto();
            foto.Id = id;
            foto.Descricao = descricao;
            foto.DataCadastro = dataCadastro;
            foto.IdAlbum = idAlbum;
            return foto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCadastro
        {
            get
            {
                return _DataCadastro;
            }
            set
            {
                OnDataCadastroChanging(value);
                ReportPropertyChanging("DataCadastro");
                _DataCadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataCadastro");
                OnDataCadastroChanged();
            }
        }
        private global::System.DateTime _DataCadastro;
        partial void OnDataCadastroChanging(global::System.DateTime value);
        partial void OnDataCadastroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAlbum
        {
            get
            {
                return _IdAlbum;
            }
            set
            {
                OnIdAlbumChanging(value);
                ReportPropertyChanging("IdAlbum");
                _IdAlbum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdAlbum");
                OnIdAlbumChanged();
            }
        }
        private global::System.Int32 _IdAlbum;
        partial void OnIdAlbumChanging(global::System.Int32 value);
        partial void OnIdAlbumChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Foto_Album", "Album")]
        public Album Album
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Album>("RedeSocialContext.FK_Foto_Album", "Album").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Album>("RedeSocialContext.FK_Foto_Album", "Album").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Album> AlbumReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Album>("RedeSocialContext.FK_Foto_Album", "Album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Album>("RedeSocialContext.FK_Foto_Album", "Album", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Comentario_Foto", "Comentario")]
        public EntityCollection<Comentario> Comentarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comentario>("RedeSocialContext.FK_Comentario_Foto", "Comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comentario>("RedeSocialContext.FK_Comentario_Foto", "Comentario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RedeSocialContext", Name="Tema")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tema : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tema object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Tema CreateTema(global::System.Int32 id, global::System.String nome)
        {
            Tema tema = new Tema();
            tema.Id = id;
            tema.Nome = nome;
            return tema;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Album_Tema", "Album")]
        public EntityCollection<Album> Albuns
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Album>("RedeSocialContext.FK_Album_Tema", "Album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Album>("RedeSocialContext.FK_Album_Tema", "Album", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RedeSocialContext", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        /// <param name="dataCadastro">Initial value of the DataCadastro property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nome, global::System.String email, global::System.DateTime dataNascimento, global::System.String senha, global::System.DateTime dataCadastro)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.Nome = nome;
            usuario.Email = email;
            usuario.DataNascimento = dataNascimento;
            usuario.Senha = senha;
            usuario.DataCadastro = dataCadastro;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCadastro
        {
            get
            {
                return _DataCadastro;
            }
            set
            {
                OnDataCadastroChanging(value);
                ReportPropertyChanging("DataCadastro");
                _DataCadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataCadastro");
                OnDataCadastroChanged();
            }
        }
        private global::System.DateTime _DataCadastro;
        partial void OnDataCadastroChanging(global::System.DateTime value);
        partial void OnDataCadastroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Album_Usuario", "Album")]
        public EntityCollection<Album> Albuns
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Album>("RedeSocialContext.FK_Album_Usuario", "Album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Album>("RedeSocialContext.FK_Album_Usuario", "Album", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "FK_Comentario_Usuario", "Comentario")]
        public EntityCollection<Comentario> Comentarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comentario>("RedeSocialContext.FK_Comentario_Usuario", "Comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comentario>("RedeSocialContext.FK_Comentario_Usuario", "Comentario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "Amizade", "Usuario1")]
        public EntityCollection<Usuario> Solicitantes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("RedeSocialContext.Amizade", "Usuario1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("RedeSocialContext.Amizade", "Usuario1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RedeSocialContext", "Amizade", "Usuario")]
        public EntityCollection<Usuario> Convidados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("RedeSocialContext.Amizade", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("RedeSocialContext.Amizade", "Usuario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
