//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("eCommerceModel", "FK_Produto_Categoria", "Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eCommerceDAL.Categoria), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eCommerceDAL.Produto), true)]
[assembly: EdmRelationshipAttribute("eCommerceModel", "FK_ItemPedido_Pedido", "Pedido", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eCommerceDAL.Pedido), "ItemPedido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eCommerceDAL.ItemPedido), true)]
[assembly: EdmRelationshipAttribute("eCommerceModel", "FK_ItemPedido_Produto", "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eCommerceDAL.Produto), "ItemPedido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eCommerceDAL.ItemPedido), true)]
[assembly: EdmRelationshipAttribute("eCommerceModel", "FK_Pedido_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eCommerceDAL.Usuario), "Pedido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eCommerceDAL.Pedido), true)]

#endregion

namespace eCommerceDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class eCommerceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new eCommerceEntities object using the connection string found in the 'eCommerceEntities' section of the application configuration file.
        /// </summary>
        public eCommerceEntities() : base("name=eCommerceEntities", "eCommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new eCommerceEntities object.
        /// </summary>
        public eCommerceEntities(string connectionString) : base(connectionString, "eCommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new eCommerceEntities object.
        /// </summary>
        public eCommerceEntities(EntityConnection connection) : base(connection, "eCommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categoria> Categorias
        {
            get
            {
                if ((_Categorias == null))
                {
                    _Categorias = base.CreateObjectSet<Categoria>("Categorias");
                }
                return _Categorias;
            }
        }
        private ObjectSet<Categoria> _Categorias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemPedido> ItensPedido
        {
            get
            {
                if ((_ItensPedido == null))
                {
                    _ItensPedido = base.CreateObjectSet<ItemPedido>("ItensPedido");
                }
                return _ItensPedido;
            }
        }
        private ObjectSet<ItemPedido> _ItensPedido;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pedido> Pedidos
        {
            get
            {
                if ((_Pedidos == null))
                {
                    _Pedidos = base.CreateObjectSet<Pedido>("Pedidos");
                }
                return _Pedidos;
            }
        }
        private ObjectSet<Pedido> _Pedidos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produto> Produtos
        {
            get
            {
                if ((_Produtos == null))
                {
                    _Produtos = base.CreateObjectSet<Produto>("Produtos");
                }
                return _Produtos;
            }
        }
        private ObjectSet<Produto> _Produtos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categorias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategorias(Categoria categoria)
        {
            base.AddObject("Categorias", categoria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItensPedido EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItensPedido(ItemPedido itemPedido)
        {
            base.AddObject("ItensPedido", itemPedido);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pedidos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPedidos(Pedido pedido)
        {
            base.AddObject("Pedidos", pedido);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produtos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProdutos(Produto produto)
        {
            base.AddObject("Produtos", produto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eCommerceModel", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categoria object.
        /// </summary>
        /// <param name="idCategoria">Initial value of the IdCategoria property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Categoria CreateCategoria(global::System.Int32 idCategoria, global::System.String descricao)
        {
            Categoria categoria = new Categoria();
            categoria.IdCategoria = idCategoria;
            categoria.Descricao = descricao;
            return categoria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCategoria
        {
            get
            {
                return _IdCategoria;
            }
            set
            {
                if (_IdCategoria != value)
                {
                    OnIdCategoriaChanging(value);
                    ReportPropertyChanging("IdCategoria");
                    _IdCategoria = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCategoria");
                    OnIdCategoriaChanged();
                }
            }
        }
        private global::System.Int32 _IdCategoria;
        partial void OnIdCategoriaChanging(global::System.Int32 value);
        partial void OnIdCategoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eCommerceModel", "FK_Produto_Categoria", "Produto")]
        public EntityCollection<Produto> Produtos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produto>("eCommerceModel.FK_Produto_Categoria", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produto>("eCommerceModel.FK_Produto_Categoria", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eCommerceModel", Name="ItemPedido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemPedido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemPedido object.
        /// </summary>
        /// <param name="idPedido">Initial value of the IdPedido property.</param>
        /// <param name="idProduto">Initial value of the IdProduto property.</param>
        /// <param name="precoUnitario">Initial value of the PrecoUnitario property.</param>
        /// <param name="quantidade">Initial value of the Quantidade property.</param>
        public static ItemPedido CreateItemPedido(global::System.Int32 idPedido, global::System.Int32 idProduto, global::System.Decimal precoUnitario, global::System.Int32 quantidade)
        {
            ItemPedido itemPedido = new ItemPedido();
            itemPedido.IdPedido = idPedido;
            itemPedido.IdProduto = idProduto;
            itemPedido.PrecoUnitario = precoUnitario;
            itemPedido.Quantidade = quantidade;
            return itemPedido;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPedido
        {
            get
            {
                return _IdPedido;
            }
            set
            {
                if (_IdPedido != value)
                {
                    OnIdPedidoChanging(value);
                    ReportPropertyChanging("IdPedido");
                    _IdPedido = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPedido");
                    OnIdPedidoChanged();
                }
            }
        }
        private global::System.Int32 _IdPedido;
        partial void OnIdPedidoChanging(global::System.Int32 value);
        partial void OnIdPedidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProduto
        {
            get
            {
                return _IdProduto;
            }
            set
            {
                if (_IdProduto != value)
                {
                    OnIdProdutoChanging(value);
                    ReportPropertyChanging("IdProduto");
                    _IdProduto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProduto");
                    OnIdProdutoChanged();
                }
            }
        }
        private global::System.Int32 _IdProduto;
        partial void OnIdProdutoChanging(global::System.Int32 value);
        partial void OnIdProdutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PrecoUnitario
        {
            get
            {
                return _PrecoUnitario;
            }
            set
            {
                OnPrecoUnitarioChanging(value);
                ReportPropertyChanging("PrecoUnitario");
                _PrecoUnitario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecoUnitario");
                OnPrecoUnitarioChanged();
            }
        }
        private global::System.Decimal _PrecoUnitario;
        partial void OnPrecoUnitarioChanging(global::System.Decimal value);
        partial void OnPrecoUnitarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantidade
        {
            get
            {
                return _Quantidade;
            }
            set
            {
                OnQuantidadeChanging(value);
                ReportPropertyChanging("Quantidade");
                _Quantidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantidade");
                OnQuantidadeChanged();
            }
        }
        private global::System.Int32 _Quantidade;
        partial void OnQuantidadeChanging(global::System.Int32 value);
        partial void OnQuantidadeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eCommerceModel", "FK_ItemPedido_Pedido", "Pedido")]
        public Pedido Pedido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedido>("eCommerceModel.FK_ItemPedido_Pedido", "Pedido").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedido>("eCommerceModel.FK_ItemPedido_Pedido", "Pedido").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pedido> PedidoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedido>("eCommerceModel.FK_ItemPedido_Pedido", "Pedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pedido>("eCommerceModel.FK_ItemPedido_Pedido", "Pedido", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eCommerceModel", "FK_ItemPedido_Produto", "Produto")]
        public Produto Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("eCommerceModel.FK_ItemPedido_Produto", "Produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("eCommerceModel.FK_ItemPedido_Produto", "Produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produto> ProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("eCommerceModel.FK_ItemPedido_Produto", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produto>("eCommerceModel.FK_ItemPedido_Produto", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eCommerceModel", Name="Pedido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pedido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pedido object.
        /// </summary>
        /// <param name="idPedido">Initial value of the IdPedido property.</param>
        /// <param name="dataHora">Initial value of the DataHora property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        public static Pedido CreatePedido(global::System.Int32 idPedido, global::System.DateTime dataHora, global::System.String status, global::System.Int32 idUsuario)
        {
            Pedido pedido = new Pedido();
            pedido.IdPedido = idPedido;
            pedido.DataHora = dataHora;
            pedido.Status = status;
            pedido.IdUsuario = idUsuario;
            return pedido;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPedido
        {
            get
            {
                return _IdPedido;
            }
            set
            {
                if (_IdPedido != value)
                {
                    OnIdPedidoChanging(value);
                    ReportPropertyChanging("IdPedido");
                    _IdPedido = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPedido");
                    OnIdPedidoChanged();
                }
            }
        }
        private global::System.Int32 _IdPedido;
        partial void OnIdPedidoChanging(global::System.Int32 value);
        partial void OnIdPedidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataHora
        {
            get
            {
                return _DataHora;
            }
            set
            {
                OnDataHoraChanging(value);
                ReportPropertyChanging("DataHora");
                _DataHora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataHora");
                OnDataHoraChanged();
            }
        }
        private global::System.DateTime _DataHora;
        partial void OnDataHoraChanging(global::System.DateTime value);
        partial void OnDataHoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eCommerceModel", "FK_ItemPedido_Pedido", "ItemPedido")]
        public EntityCollection<ItemPedido> ItensPedido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemPedido>("eCommerceModel.FK_ItemPedido_Pedido", "ItemPedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemPedido>("eCommerceModel.FK_ItemPedido_Pedido", "ItemPedido", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eCommerceModel", "FK_Pedido_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("eCommerceModel.FK_Pedido_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("eCommerceModel.FK_Pedido_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("eCommerceModel.FK_Pedido_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("eCommerceModel.FK_Pedido_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eCommerceModel", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produto object.
        /// </summary>
        /// <param name="idProduto">Initial value of the IdProduto property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="preco">Initial value of the Preco property.</param>
        /// <param name="idCategoria">Initial value of the IdCategoria property.</param>
        public static Produto CreateProduto(global::System.Int32 idProduto, global::System.String nome, global::System.Decimal preco, global::System.Int32 idCategoria)
        {
            Produto produto = new Produto();
            produto.IdProduto = idProduto;
            produto.Nome = nome;
            produto.Preco = preco;
            produto.IdCategoria = idCategoria;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProduto
        {
            get
            {
                return _IdProduto;
            }
            set
            {
                if (_IdProduto != value)
                {
                    OnIdProdutoChanging(value);
                    ReportPropertyChanging("IdProduto");
                    _IdProduto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProduto");
                    OnIdProdutoChanged();
                }
            }
        }
        private global::System.Int32 _IdProduto;
        partial void OnIdProdutoChanging(global::System.Int32 value);
        partial void OnIdProdutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Preco
        {
            get
            {
                return _Preco;
            }
            set
            {
                OnPrecoChanging(value);
                ReportPropertyChanging("Preco");
                _Preco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Preco");
                OnPrecoChanged();
            }
        }
        private global::System.Decimal _Preco;
        partial void OnPrecoChanging(global::System.Decimal value);
        partial void OnPrecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCategoria
        {
            get
            {
                return _IdCategoria;
            }
            set
            {
                OnIdCategoriaChanging(value);
                ReportPropertyChanging("IdCategoria");
                _IdCategoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCategoria");
                OnIdCategoriaChanged();
            }
        }
        private global::System.Int32 _IdCategoria;
        partial void OnIdCategoriaChanging(global::System.Int32 value);
        partial void OnIdCategoriaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eCommerceModel", "FK_Produto_Categoria", "Categoria")]
        public Categoria Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("eCommerceModel.FK_Produto_Categoria", "Categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("eCommerceModel.FK_Produto_Categoria", "Categoria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categoria> CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("eCommerceModel.FK_Produto_Categoria", "Categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categoria>("eCommerceModel.FK_Produto_Categoria", "Categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eCommerceModel", "FK_ItemPedido_Produto", "ItemPedido")]
        public EntityCollection<ItemPedido> ItensPedido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemPedido>("eCommerceModel.FK_ItemPedido_Produto", "ItemPedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemPedido>("eCommerceModel.FK_ItemPedido_Produto", "ItemPedido", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eCommerceModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        /// <param name="cPF">Initial value of the CPF property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        /// <param name="telefoneFixo">Initial value of the TelefoneFixo property.</param>
        /// <param name="telefoneMovel">Initial value of the TelefoneMovel property.</param>
        /// <param name="endLogradouro">Initial value of the EndLogradouro property.</param>
        /// <param name="endNumero">Initial value of the EndNumero property.</param>
        /// <param name="endBairro">Initial value of the EndBairro property.</param>
        /// <param name="endCidade">Initial value of the EndCidade property.</param>
        /// <param name="endUF">Initial value of the EndUF property.</param>
        /// <param name="dataCadastro">Initial value of the DataCadastro property.</param>
        public static Usuario CreateUsuario(global::System.Int32 idUsuario, global::System.String nome, global::System.String email, global::System.String senha, global::System.String cPF, global::System.DateTime dataNascimento, global::System.String telefoneFixo, global::System.String telefoneMovel, global::System.String endLogradouro, global::System.String endNumero, global::System.String endBairro, global::System.String endCidade, global::System.String endUF, global::System.DateTime dataCadastro)
        {
            Usuario usuario = new Usuario();
            usuario.IdUsuario = idUsuario;
            usuario.Nome = nome;
            usuario.Email = email;
            usuario.Senha = senha;
            usuario.CPF = cPF;
            usuario.DataNascimento = dataNascimento;
            usuario.TelefoneFixo = telefoneFixo;
            usuario.TelefoneMovel = telefoneMovel;
            usuario.EndLogradouro = endLogradouro;
            usuario.EndNumero = endNumero;
            usuario.EndBairro = endBairro;
            usuario.EndCidade = endCidade;
            usuario.EndUF = endUF;
            usuario.DataCadastro = dataCadastro;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TelefoneFixo
        {
            get
            {
                return _TelefoneFixo;
            }
            set
            {
                OnTelefoneFixoChanging(value);
                ReportPropertyChanging("TelefoneFixo");
                _TelefoneFixo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TelefoneFixo");
                OnTelefoneFixoChanged();
            }
        }
        private global::System.String _TelefoneFixo;
        partial void OnTelefoneFixoChanging(global::System.String value);
        partial void OnTelefoneFixoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TelefoneMovel
        {
            get
            {
                return _TelefoneMovel;
            }
            set
            {
                OnTelefoneMovelChanging(value);
                ReportPropertyChanging("TelefoneMovel");
                _TelefoneMovel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TelefoneMovel");
                OnTelefoneMovelChanged();
            }
        }
        private global::System.String _TelefoneMovel;
        partial void OnTelefoneMovelChanging(global::System.String value);
        partial void OnTelefoneMovelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EndLogradouro
        {
            get
            {
                return _EndLogradouro;
            }
            set
            {
                OnEndLogradouroChanging(value);
                ReportPropertyChanging("EndLogradouro");
                _EndLogradouro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EndLogradouro");
                OnEndLogradouroChanged();
            }
        }
        private global::System.String _EndLogradouro;
        partial void OnEndLogradouroChanging(global::System.String value);
        partial void OnEndLogradouroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EndNumero
        {
            get
            {
                return _EndNumero;
            }
            set
            {
                OnEndNumeroChanging(value);
                ReportPropertyChanging("EndNumero");
                _EndNumero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EndNumero");
                OnEndNumeroChanged();
            }
        }
        private global::System.String _EndNumero;
        partial void OnEndNumeroChanging(global::System.String value);
        partial void OnEndNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EndComplemento
        {
            get
            {
                return _EndComplemento;
            }
            set
            {
                OnEndComplementoChanging(value);
                ReportPropertyChanging("EndComplemento");
                _EndComplemento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EndComplemento");
                OnEndComplementoChanged();
            }
        }
        private global::System.String _EndComplemento;
        partial void OnEndComplementoChanging(global::System.String value);
        partial void OnEndComplementoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EndBairro
        {
            get
            {
                return _EndBairro;
            }
            set
            {
                OnEndBairroChanging(value);
                ReportPropertyChanging("EndBairro");
                _EndBairro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EndBairro");
                OnEndBairroChanged();
            }
        }
        private global::System.String _EndBairro;
        partial void OnEndBairroChanging(global::System.String value);
        partial void OnEndBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EndCidade
        {
            get
            {
                return _EndCidade;
            }
            set
            {
                OnEndCidadeChanging(value);
                ReportPropertyChanging("EndCidade");
                _EndCidade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EndCidade");
                OnEndCidadeChanged();
            }
        }
        private global::System.String _EndCidade;
        partial void OnEndCidadeChanging(global::System.String value);
        partial void OnEndCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EndUF
        {
            get
            {
                return _EndUF;
            }
            set
            {
                OnEndUFChanging(value);
                ReportPropertyChanging("EndUF");
                _EndUF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EndUF");
                OnEndUFChanged();
            }
        }
        private global::System.String _EndUF;
        partial void OnEndUFChanging(global::System.String value);
        partial void OnEndUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCadastro
        {
            get
            {
                return _DataCadastro;
            }
            set
            {
                OnDataCadastroChanging(value);
                ReportPropertyChanging("DataCadastro");
                _DataCadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataCadastro");
                OnDataCadastroChanged();
            }
        }
        private global::System.DateTime _DataCadastro;
        partial void OnDataCadastroChanging(global::System.DateTime value);
        partial void OnDataCadastroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eCommerceModel", "FK_Pedido_Usuario", "Pedido")]
        public EntityCollection<Pedido> Pedidos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pedido>("eCommerceModel.FK_Pedido_Usuario", "Pedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pedido>("eCommerceModel.FK_Pedido_Usuario", "Pedido", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
